version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
      steps:
        - checkout
        - node/install-packages
        - node/test
